//
//  HomeView.swift
//  extensiLE
//
//  Created by Becca GW on 2023-02-28.
//

import SwiftUI

struct HomeView: View {
    var body: some View {
            ZStack {
                Color.black
                    .ignoresSafeArea()
                
                VStack(alignment: .center) {
                    Image("extensiLE Logo V4")
                        .resizable()
                        .frame(width: 200, height: 80, alignment: .center)
                        .padding()
                    
//                NavigationView {
//                    Text("My app")
//                    .toolbar {
//                        ToolbarItemGroup(placement: .bottomBar) {
//                            HStack {
//                                VStack {
//                                    Image(systemName: "house")
////                                        .background(CustomColors.MenuColor)
////                                        .frame(width: 150, height: 150)
//                                    Text("Home")
//                                }
//                            Spacer()
//                                VStack {
//                                    Image(systemName: "plus.circle")
////                                        .background(CustomColors.MenuColor)
////                                        .frame(width: 150, height: 150)
//                                    Text("Record")
//                                }
//                            Spacer()
//                                VStack {
//                                    Image(systemName: "figure.tennis")
////                                        .background(CustomColors.MenuColor)
////                                        .frame(width: 150, height: 150)
//                                    Text("Education")
//                                }
//                            Spacer()
//                                VStack {
//                                    Image(systemName: "person")
////                                        .background(CustomColors.MenuColor)
////                                        .frame(width: 150, height: 150)
//                                    Text("Account")
//                                }
//                            }
//
//                            }
//                        }
//                    }
//                .background(Color(red: 0, green: 0, blue: 0))
//
////                    Image("extensiLE Logo V4")
////                        .resizable()
////                        .frame(width: 200, height: 80, alignment: .center)
////                        .padding()
////                    .position(x: 195, y: 79.80099487304688)
////                Text("May 13, 2022")
////                    .font(.custom("Inter", size: 16))
////                    .foregroundColor(Color(red: 0.67, green: 0.88, blue: 1))
////                Text("Duration")
////                    .font(.custom("Inter", size: 16))
////                    .foregroundColor(Color(red: 0.67, green: 0.88, blue: 1))
////                Text("10° Flexion")
////                    .font(.custom("Inter", size: 16))
////                    .foregroundColor(Color(red: 0.58, green: 0.63, blue: 0.66))
////                Text("56m 01s")
////                    .font(.custom("Inter", size: 16))
////                    .foregroundColor(Color(red: 0.58, green: 0.63, blue: 0.66))
////                Text("Average Angle")
////                    .font(.custom("Inter", size: 16))
////                    .foregroundColor(Color(red: 0.67, green: 0.88, blue: 1))
////                Text("Medium")
////                    .font(.custom("Inter", size: 16))
////                    .foregroundColor(Color(red: 0.58, green: 0.63, blue: 0.66))
////                Text("Tensile Insert")
//                    .font(.custom("Inter", size: 16))
//                    .foregroundColor(Color(red: 0.67, green: 0.88, blue: 1))
//                Divider()
//                Divider()
//                Divider()
//                Divider()
//                Text("Time (mins)")
//                    .font(.custom("Inter", size: 12))
//                    .foregroundColor(Color(red: 1, green: 1, blue: 1))
//                Divider()
//                Divider()
//                Divider()
//                Divider()
//                Divider()
//                Divider()
//                Divider()
//                Divider()
//                Divider()
//                Divider()
//                Divider()
//                Divider()
//                Divider()
//                Divider()
//                Divider()
//                Divider()
//                Divider()
//                Divider()
//                Divider()
//                Divider()
//                Divider()
//                Divider()
//                Divider()
//                Text("-40.0")
//                    .font(.custom("Inter", size: 6))
//                    .foregroundColor(Color(red: 1, green: 1, blue: 1))
//                Text("-30.0")
//                    .font(.custom("Inter", size: 6))
//                    .foregroundColor(Color(red: 1, green: 1, blue: 1))
//                Text("-20.0")
//                    .font(.custom("Inter", size: 6))
//                    .foregroundColor(Color(red: 1, green: 1, blue: 1))
//                Text("-10.0")
//                    .font(.custom("Inter", size: 6))
//                    .foregroundColor(Color(red: 1, green: 1, blue: 1))
//                Text("0.0")
//                    .font(.custom("Inter", size: 6))
//                    .foregroundColor(Color(red: 1, green: 1, blue: 1))
//                Text("10.0")
//                    .font(.custom("Inter", size: 6))
//                    .foregroundColor(Color(red: 1, green: 1, blue: 1))
//                Text("20.0")
//                    .font(.custom("Inter", size: 6))
//                    .foregroundColor(Color(red: 1, green: 1, blue: 1))
//                Text("30.0")
//                    .font(.custom("Inter", size: 6))
//                    .foregroundColor(Color(red: 1, green: 1, blue: 1))
//                Text("40.0")
//                    .font(.custom("Inter", size: 6))
//                    .foregroundColor(Color(red: 1, green: 1, blue: 1))
//                Text("40.0")
//                    .font(.custom("Inter", size: 6))
//                    .foregroundColor(Color(red: 1, green: 1, blue: 1))
//                Text("20.0")
//                    .font(.custom("Inter", size: 6))
//                    .foregroundColor(Color(red: 1, green: 1, blue: 1))
//                Text("32.0")
//                    .font(.custom("Inter", size: 6))
//                    .foregroundColor(Color(red: 1, green: 1, blue: 1))
//                Text("44.0")
//                    .font(.custom("Inter", size: 6))
//                    .foregroundColor(Color(red: 1, green: 1, blue: 1))
//                Text("4.0")
//                    .font(.custom("Inter", size: 6))
//                    .foregroundColor(Color(red: 1, green: 1, blue: 1))
//                Text("36.0")
//                    .font(.custom("Inter", size: 6))
//                    .foregroundColor(Color(red: 1, green: 1, blue: 1))
//                Text("48.0")
//                    .font(.custom("Inter", size: 6))
//                    .foregroundColor(Color(red: 1, green: 1, blue: 1))
//                Text("52.0")
//                    .font(.custom("Inter", size: 6))
//                    .foregroundColor(Color(red: 1, green: 1, blue: 1))
//                Text("56.0")
//                    .font(.custom("Inter", size: 6))
//                    .foregroundColor(Color(red: 1, green: 1, blue: 1))
//                Text("8.0")
//                    .font(.custom("Inter", size: 6))
//                    .foregroundColor(Color(red: 1, green: 1, blue: 1))
//                Text("28.0")
//                    .font(.custom("Inter", size: 6))
//                    .foregroundColor(Color(red: 1, green: 1, blue: 1))
//                Text("12.0")
//                    .font(.custom("Inter", size: 6))
//                    .foregroundColor(Color(red: 1, green: 1, blue: 1))
//                Text("16.0")
//                    .font(.custom("Inter", size: 6))
//                    .foregroundColor(Color(red: 1, green: 1, blue: 1))
//                Text("24.0")
//                    .font(.custom("Inter", size: 6))
//                    .foregroundColor(Color(red: 1, green: 1, blue: 1))
//                Divider()
//                Text("Wrist Angle (Extension -/Flexion +)")
//                    .font(.custom("Inter", size: 12))
//                    .foregroundColor(Color(red: 1, green: 1, blue: 1))
//                Text("Duration")
//                    .font(.custom("Inter", size: 16))
//                    .foregroundColor(Color(red: 0.67, green: 0.88, blue: 1))
//                Text("10° Flexion")
//                    .font(.custom("Inter", size: 16))
//                    .foregroundColor(Color(red: 0.58, green: 0.63, blue: 0.66))
//                Text("56m 01s")
//                    .font(.custom("Inter", size: 16))
//                    .foregroundColor(Color(red: 0.58, green: 0.63, blue: 0.66))
//                Text("Average Angle")
//                    .font(.custom("Inter", size: 16))
//                    .foregroundColor(Color(red: 0.67, green: 0.88, blue: 1))
//                Text("Medium")
//                    .font(.custom("Inter", size: 16))
//                    .foregroundColor(Color(red: 0.58, green: 0.63, blue: 0.66))
//                Text("Tensile Insert")
//                    .font(.custom("Inter", size: 16))
//                    .foregroundColor(Color(red: 0.67, green: 0.88, blue: 1))
//                Divider()
//                Divider()
//                Text("May 1, 2022")
//                    .font(.custom("Inter", size: 16))
//                    .foregroundColor(Color(red: 0.67, green: 0.88, blue: 1))
//                Divider()
//                Divider()
//                Divider()
//                Divider()
//                Divider()
//                Divider()
//                Divider()
//                Divider()
//                Text("-30.0")
//                    .font(.custom("Inter", size: 6))
//                    .foregroundColor(Color(red: 1, green: 1, blue: 1))
//                Text("-20.0")
//                    .font(.custom("Inter", size: 6))
//                    .foregroundColor(Color(red: 1, green: 1, blue: 1))
//                Text("-10.0")
//                    .font(.custom("Inter", size: 6))
//                    .foregroundColor(Color(red: 1, green: 1, blue: 1))
//                Text("0.0")
//                    .font(.custom("Inter", size: 6))
//                    .foregroundColor(Color(red: 1, green: 1, blue: 1))
//                Text("10.0")
//                    .font(.custom("Inter", size: 6))
//                    .foregroundColor(Color(red: 1, green: 1, blue: 1))
//                Text("20.0")
//                    .font(.custom("Inter", size: 6))
//                    .foregroundColor(Color(red: 1, green: 1, blue: 1))
//                Text("40.0")
//                    .font(.custom("Inter", size: 6))
//                    .foregroundColor(Color(red: 1, green: 1, blue: 1))
//                Text("30.0")
//                    .font(.custom("Inter", size: 6))
//                    .foregroundColor(Color(red: 1, green: 1, blue: 1))
//                Divider()
//                ZStack {
//                }
//                .background(Color(red: 1, green: 1, blue: 1))
//                Text("Account")
//                    .font(.custom("Inter", size: 10))
//                    .foregroundColor(Color(red: 0.68, green: 0.76, blue: 0.80))
//                ZStack {
//                }
//                .background(Color(red: 1, green: 1, blue: 1))
//                Text("Record")
//                    .font(.custom("Inter", size: 10))
//                    .foregroundColor(Color(red: 0.68, green: 0.76, blue: 0.80))
//                Text("Home")
//                    .font(.custom("Inter", size: 10))
//                    .foregroundColor(Color(red: 0.68, green: 0.76, blue: 0.80))
//                ZStack {
//                }
//                .background(Color(red: 1, green: 1, blue: 1))
//                ZStack {
//                }
//                .background(Color(red: 1, green: 1, blue: 1))
//                Text("Education")
//                    .font(.custom("Inter", size: 10))
//                    .foregroundColor(Color(red: 0.68, green: 0.76, blue: 0.80))
            }
            .background(Color(red: 0, green: 0, blue: 0))
        }
    }
}

struct HomeView_Previews: PreviewProvider {
    static var previews: some View {
        HomeView()
    }
}
